# Pandas

Python Data Analysis Library. It makes use of Series (Like a Numpy Array) and DataFrame (tabular data 表格式). In this lesson, we will learn the basic data processing, calculation and filtering by using Pandas.

- [Is student passed?](#Is-student-passed?)
- [Accessing the column](#Accessing-the-column)
- [Reading Excel](#Reading-Excel)
- [Reading CSV](#Reading-CSV)
- [Fetching CSV from Wikipedia](#Fetching-CSV-from-Wikipedia)
- [Lab 4: Olymnic Games medal table](#Lab-4:-All-time-Olympic-Games-medal-table)

In [1]:
import numpy as np
import pandas as pd

## Is student passed?

Remember the `pass_or_fail` function we defined in lesson 2? Now we can further process this example with Pandas and its DataFrame.

In [2]:
# Apply label to data
def pass_or_fail(x):
    if x >= 60:
        return True
    return False

In [3]:
# Prepare the data
data = [50, 60, 20, 50, 88, 45, 63, 59]

Given the data list, we can convert it into DataFrame

In [4]:
# Where is the pass and fail?
df = pd.DataFrame(data, columns=['Score'])
df

   Score
0     50
1     60
2     20
3     50
4     88
5     45
6     63
7     59

We can create extra column to indicate if the score is passed.

In [5]:
df['Is Passed'] = df['Score'].apply(pass_or_fail)
df

   Score  Is Passed
0     50      False
1     60       True
2     20      False
3     50      False
4     88       True
5     45      False
6     63       True
7     59      False

By using Boolean filtering, we can list only the data that meet the condition.

In [6]:
df[ (df['Score']>=60) & (df['Score']<=80) ]

   Score  Is Passed
1     60       True
6     63       True

Next, we will load the students dictionary from lesson 2.

In [7]:
students = [
    {'name': 'Thomas', 'score': 65},
    {'name': 'Alan', 'score': 95},
    {'name': 'Jane', 'score': 85},
    {'name': 'Susan', 'score': 75},
    {'name': 'Chris', 'score': 45}
]

We convert the dictionary into DataFrame. Pandas will take care of the column name automatically.

In [8]:
df = pd.DataFrame(students)
df

     name  score
0  Thomas     65
1    Alan     95
2    Jane     85
3   Susan     75
4   Chris     45

Same as the example above, we apply the `pass_or_fail` function to create a new column with Boolean.

In [9]:
df['Is Passed'] = df['score'].apply(pass_or_fail)
df

     name  score  Is Passed
0  Thomas     65       True
1    Alan     95       True
2    Jane     85       True
3   Susan     75       True
4   Chris     45      False

We can generate a new DataFrame with only the passed records.

In [10]:
df_passed = df[df["Is Passed"]]
df_passed

     name  score  Is Passed
0  Thomas     65       True
1    Alan     95       True
2    Jane     85       True
3   Susan     75       True

We can save the processed tabular data into Excel by using `to_excel`.

In [11]:

df_passed.to_excel("Students Passed.xlsx")

## Accessing the column

We can get the name of students who passed.

In [12]:
df[df["Is Passed"]]["name"]

0    Thomas
1      Alan
2      Jane
3     Susan
Name: name, dtype: object

An example of outputing the result.

In [13]:
count_of_passed = len(df[df["Is Passed"]])
result = f"We have total {len(df)} students, {count_of_passed} of them passed."
print(result)

We have total 5 students, 4 of them passed.

In [14]:
names = ', '.join(df[df["Is Passed"]]["name"])
names = f"They are {names}."

print(names)

They are Thomas, Alan, Jane, Susan.

## Reading Excel

In [15]:
df = pd.read_excel('visitors.xlsx')
df

    Time  Visitors
0      1         2
1      2         0
2      3         1
3      4         3
4      5         0
5      6         8
6      7        32
7      8        48
8      9        21
9     10        10
10    11         9
11    12        47
12    13        42
13    14        15
14    15        11
15    16        12
16    17        19
17    18        55
18    19        57
19    20        55
20    21        32
21    22        24
22    23        11
23    24         4

In [16]:
df.head()

   Time  Visitors
0     1         2
1     2         0
2     3         1
3     4         3
4     5         0

In [17]:
df.tail()

    Time  Visitors
19    20        55
20    21        32
21    22        24
22    23        11
23    24         4

In [18]:
df['Visitors']

0      2
1      0
2      1
3      3
4      0
5      8
6     32
7     48
8     21
9     10
10     9
11    47
12    42
13    15
14    11
15    12
16    19
17    55
18    57
19    55
20    32
21    24
22    11
23     4
Name: Visitors, dtype: int64

Which hours do we have more than 30 visitors?

In [19]:
df[ df['Visitors'] > 30 ]

    Time  Visitors
6      7        32
7      8        48
11    12        47
12    13        42
17    18        55
18    19        57
19    20        55
20    21        32

We can create new Boolean column with condition.

In [20]:
df['Good Timing'] = df['Visitors']>30

In [21]:
df

    Time  Visitors  Good Timing
0      1         2        False
1      2         0        False
2      3         1        False
3      4         3        False
4      5         0        False
5      6         8        False
6      7        32         True
7      8        48         True
8      9        21        False
9     10        10        False
10    11         9        False
11    12        47         True
12    13        42         True
13    14        15        False
14    15        11        False
15    16        12        False
16    17        19        False
17    18        55         True
18    19        57         True
19    20        55         True
20    21        32         True
21    22        24        False
22    23        11        False
23    24         4        False

In [22]:
df[df['Good Timing']]

    Time  Visitors  Good Timing
6      7        32         True
7      8        48         True
11    12        47         True
12    13        42         True
17    18        55         True
18    19        57         True
19    20        55         True
20    21        32         True

## Reading CSV

In [23]:
df = pd.read_csv('visitors.csv', delimiter=',', names=('date','visitors'))

df.head()

         date  visitors
0  2018-12-18        22
1  2018-12-17         0
2  2018-12-16         4
3  2018-12-15       218
4  2018-12-14        11

In [24]:
df['date'].head()

0    2018-12-18
1    2018-12-17
2    2018-12-16
3    2018-12-15
4    2018-12-14
Name: date, dtype: object

## Fetching CSV from Wikipedia

We can convert the data table into CSV by using https://wikitable2csv.ggor.de

For example, we can download the All-time Olympic Games medal table from Wikipedia:

https://en.wikipedia.org/wiki/All-time_Olympic_Games_medal_table

We can load the converted CSV directly into pandas and process the data set. Alternatively, we can clean up the CSV a little bit before loading it into pandas.

For instance, we can give each column a readable name in header. We can also convert thousands with comma too.

## Lab 4: All-time Olympic Games medal table

We have prepared a `table-1-olympics.csv` file with basic format processed.

In [25]:
df = pd.read_csv('table-1-olympics.csv')
df = df[:-1] # Remove the last row of data
df.head()

,Team,Summer Games,Gold,Silver,Bronze,Total,Winter Games,Gold.1,Silver.1,Bronze.1,Total.1,Combined Participated,Combined Gold,Combined Silver,Combined Bronze,Combined Total
0,Afghanistan (AFG),14,0,0,2,2,0,0,0,0,0,14,0,0,2,2
1,Algeria (ALG),13,5,4,8,17,3,0,0,0,0,16,5,4,8,17
2,Argentina (ARG),24,21,25,28,74,19,0,0,0,0,43,21,25,28,74
3,Armenia (ARM),6,2,6,6,14,7,0,0,0,0,13,2,6,6,14
4,Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

In [26]:
df.shape

(152, 16)

By checking the `dtype`, we find that the data in "O" instead of "Int". "O" stands for Object because it is treated as String.

In [27]:
df['Total'].dtype

dtype('O')

We can convert the dtype by using `astype`.

In [28]:
df['Total'] = df['Total'].astype(int)

In [29]:
df['Total'].dtype

dtype('int64')

Now the team name is not quite readable. There are extra symbols and footnote indicators.

We can clean up `Team` name and replace space into underscore:

In [30]:
df["Team"] = df["Team"].apply(lambda x: x.split("(")[0].strip().replace(" ","_"))

In [31]:
df.head()

,Team,Summer Games,Gold,Silver,Bronze,Total,Winter Games,Gold.1,Silver.1,Bronze.1,Total.1,Combined Participated,Combined Gold,Combined Silver,Combined Bronze,Combined Total
0,Afghanistan,14,0,0,2,2,0,0,0,0,0,14,0,0,2,2
1,Algeria,13,5,4,8,17,3,0,0,0,0,16,5,4,8,17
2,Argentina,24,21,25,28,74,19,0,0,0,0,43,21,25,28,74
3,Armenia,6,2,6,6,14,7,0,0,0,0,13,2,6,6,14
4,Australasia,2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

Set the Team name as dataframe index:

In [32]:
df.set_index("Team", inplace=True)

Make sure all numbers in the dataframe are numeric:

In [33]:
df = df.astype(int)

We can inspect the column names by using `df.columns`

|Expected result|
|---|
|Index(['Summer Games', 'Gold', 'Silver', 'Bronze', 'Total', 'Winter Games',
       'Gold.1', 'Silver.1', 'Bronze.1', 'Total.1', 'Combined Participated',
       'Combined Gold', 'Combined Silver', 'Combined Bronze',
       'Combined Total'],
      dtype='object')|

We can access a particular row of data by using `iloc`

In [34]:
df.iloc[16]

Summer Games              22
Gold                      30
Silver                    36
Bronze                    63
Total                    129
Winter Games               8
Gold.1                     0
Silver.1                   0
Bronze.1                   0
Total.1                    0
Combined Participated     30
Combined Gold             30
Combined Silver           36
Combined Bronze           63
Combined Total           129
Name: Brazil, dtype: int64

We can also access a particular row of data by using the index label `df.loc["Brazil"]`.

What is the Olymnpic Medal data from China?

|Expected result|
|---|
|Summer Games              10
Gold                     224
Silver                   167
Bronze                   155
Total                    546
Winter Games              11
Gold.1                    13
Silver.1                  28
Bronze.1                  21
Total.1                   62
Combined Participated     21
Combined Gold            237
Combined Silver          195
Combined Bronze          176
Combined Total           608
Name: China, dtype: int32|

How many gold medal China won in Summer Olymnpics?

|Expected result|
|---|
|224|

We can get the rank of gold medal list by using `df.sort_values`.

In [35]:
df.sort_values(by="Gold", ascending=False)[:5]

,Summer Games,Gold,Silver,Bronze,Total,Winter Games,Gold.1,Silver.1,Bronze.1,Total.1,Combined Participated,Combined Gold,Combined Silver,Combined Bronze,Combined Total
Team,,,,,,,,,,,,,,,
United_States,27,1022,795,705,2522,23,105,112,88,305,50,1127,907,793,2827
Soviet_Union,9,395,319,296,1010,9,78,57,59,194,18,473,376,355,1204
Great_Britain,28,263,295,293,851,23,11,4,17,32,51,274,299,310,883
China,10,224,167,155,546,11,13,28,21,62,21,237,195,176,608
France,28,212,241,263,716,23,36,35,53,124,51,248,276,316,840

How many teams earn gold medals in both summer Olympics and winder Olympics?

In [36]:
len(df[(df["Gold"] > 0) & (df["Gold.1"] > 0)])

38

Which teams are they?

In [37]:
df[(df["Gold"] > 0) & (df["Gold.1"] > 0)][['Gold','Gold.1']]

                        Gold  Gold.1
Team
Australia                147       5
Austria                   18      64
Belarus                   12       8
Belgium                   40       1
Bulgaria                  51       1
Canada                    64      73
China                    224      13
Croatia                   11       4
Czech_Republic            15       9
Czechoslovakia            49       2
Estonia                    9       4
Finland                  101      43
France                   212      36
Germany                  191      92
United_Team_of_Germany    28       8
East_Germany             153      39
West_Germany              56      11
Great_Britain            263      11
Hungary                  175       1
Italy                    206      40
Japan                    142      14
Kazakhstan                15       1
South_Korea               90      31
Latvia                     3       1
Netherlands               85      45
Norway                    56     132
Poland                    68       7
Russia                   148      47
Soviet_Union             395      78
Slovakia                   9       3
Slovenia                   5       2
Spain                     45       1
Sweden                   145      57
Switzerland               50      56
Ukraine                   35       3
United_States           1022     105
Uzbekistan                 8       1
Unified_Team              45       9

How about the team that wins gold medals in winter Olympics but not summer Olympics?

|Expected result|
|---|
|['Liechtenstein', 'Olympic_Athletes_from_Russia']|

---

## Summary

In this lesson, we learn to process tabular data by using Pandas.

## pandas--对axis=0,axis=1的理解
![](img/pandas_axis.jpg)

In [18]:
df = pd.DataFrame([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]], \
columns=["col1", "col2", "col3", "col4"])
df.mean(axis=1) #均值
df.drop("col4", axis=1)

   col1  col2  col3
0    11    12    13
1    21    22    23
2    31    32    33

# pandas 處理xlsx資料

In [ ]:
import pandas as pd
df=pd.read_excel('ref/lesson-8-numpy-and-pandas/visitors.xlsx',index_col=0)   

#column name & type
for column_name in df: print(r"{}{}".format(type(column_name),column_name))
    
# iterate items
for column_name, item in df.iteritems():
    print(r"{}{}".format(type(column_name),column_name))
    print(type(item))
    print(item)
    print('------')   
    break

# colunm name 
print("('{}'),".format("','".join(str(column_name).replace("'","") for column_name in df)))

# iterate rows
for index, row in df.iterrows():
    print("('{}'),".format("','".join(str(r).replace("'","") for r in row)))

In [3]:
import pandas as pd
df=pd.read_excel('kw_data.xlsx',index_col=0)   
df

,性別,年齡,身高,體重,BMI,右腹股溝韌帶邊緣內側(無重叠),A內下,A外下,A上下,Ast50pr,...,C1,左韌帶下方2CM內側,D內下,D外下,D上下,Dst50pr,Dgt50pr,D1,D雙側,D重叠率*
編號,,,,,,,,,,,,,,,,,,,,,
1,M,68,157,62,25.153150,NaN,X,NaN,NaN,X,...,NaN,NaN,NaN,X,NaN,X,NaN,NaN,NaN,NaN
2,M,57,168,93,32.950680,NaN,X,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,X,NaN,NaN,X,NaN,NaN
3,M,58,162,68,25.910684,NaN,X,NaN,NaN,X,...,X,NaN,NaN,NaN,X,NaN,NaN,X,上下,100
4,M,43,167,72,25.816630,X,NaN,NaN,NaN,NaN,...,NaN,NaN,X,NaN,NaN,NaN,X,NaN,NaN,NaN
5,M,59,159,55,21.755469,X,NaN,NaN,NaN,NaN,...,X,NaN,NaN,NaN,X,NaN,NaN,X,上下,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,M,40,168,66,23.384354,X,NaN,NaN,NaN,NaN,...,NaN,NaN,X,NaN,NaN,NaN,X,NaN,內下,>50
139,F,87,142,48,23.804801,NaN,X,NaN,NaN,X,...,X,NaN,NaN,NaN,X,NaN,NaN,X,上下,NaN
140,M,71,142,33,16.365800,X,NaN,NaN,NaN,NaN,...,NaN,NaN,X,NaN,NaN,X,NaN,NaN,內下,<50
141,F,97,150,64,28.444444,NaN,X,NaN,NaN,X,...,NaN,NaN,NaN,X,NaN,NaN,X,NaN,外下,NaN
142,F,83,173,74,24.725183,X,NaN,NaN,NaN,NaN,...,X,NaN,NaN,NaN,X,NaN,NaN,X,上下,100

In [20]:
from IPython.display import Latex,HTML,Markdown
#df.dtypes
df1 = df[(df["性別"]=="M") & ((df["BMI"]>=18.0) & (df["BMI"]<=22.0))]
df1=  df1=="X" 
sum_s=df1.sum(axis=0)
display(sum_s)
#display(Markdown("{}\n{}\n{}".format("|".join(sum_s.index),"|".join("--" for _ in sum_s.index),"|".join(str(v) for i, v in sum_s.items()))))

性別                   0
年齡                   0
身高                   0
體重                   0
BMI                  0
右腹股溝韌帶邊緣內側(無重叠)     14
A內下                  8
A外下                  0
A上下                  0
Ast50pr              8
Agt50pr              0
A1                   0
左腹股溝韌帶邊緣左內側(無重叠)    11
B內下                 11
B外下                  0
B上下                  0
Bst50pr             10
Bgt50pr              1
B1                   0
B雙側                  0
B重叠率*                0
右韌帶下方2CM內側           2
C內下                 13
C外下                  2
C上下                  5
Cst50pr              9
Cgt50pr              6
C1                   5
左韌帶下方2CM內側           0
D內下                 16
D外下                  2
D上下                  4
Dst50pr             11
Dgt50pr              7
D1                   4
D雙側                  0
D重叠率*                0
dtype: int64